name: Docs

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Requirements
        shell: bash
        run: brew install cmake doxygen
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Configure Cmake
        shell: bash
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DPOLY_BUILD_DOC=ON
      - name: Build docs
        shell: bash
        run: |
          cmake \
            --build ./build \
            --config Release \
            --target docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.DEPLOY_TO_PAGES }}
          branch: main
          folder: ./build/docs/html
          repository-name: gabrielepongelli/gabrielepongelli.github.io
          target-folder: ./docs/poly
