name: Docs

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Requirements
        shell: bash
        run: brew install cmake doxygen
      - name: Checkout repo
        uses: actions/checkout@1.0.0
      - name: Configure Cmake
        shell: bash
        run: |
          cmake \
            -S . \
            -B ./build \
            -DCMAKE_BUILD_TYPE=Release \
            -DPOLY_BUILD_DOC=ON
      - name: Build docs
        shell: bash
        run: |
          cmake \
            --build ./build 
            --config Release 
            --target docs
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: ./build/docs/html
